edition       = "2024"
style_edition = "2024"

group_imports        = "StdExternalCrate"
imports_granularity  = "Module"
imports_layout       = "HorizontalVertical"
reorder_impl_items   = true
unstable_features    = true
use_small_heuristics = "Max"
