[package]
  authors.workspace    = true
  description          = "Compiler for the Typhon programming language"
  edition.workspace    = true
  license.workspace    = true
  name                 = "typhon-compiler"
  repository.workspace = true
  version.workspace    = true

[dependencies]
  # Lexer
  logos             = "0.14.0" # Fast lexer generator
  unic-ucd-category = "0.9.0"  # Unicode character categories
  unicode-xid       = "0.2.4"  # Unicode identifier detection

  # Parser
  chumsky   = "0.9.3"                                     # Ergonomic parser combinators
  miette    = { version = "7.0.0", features = ["fancy"] } # Error reporting
  thiserror = "1.0.56"                                    # Error handling

  # General utilities
  bitflags     = "2.4.1"
  indenter     = "0.3.3"                                       # Indentation management
  paste        = "1.0.14"
  rustc-hash   = "1.1.0"                                       # Fast hash maps
  strum        = { version = "0.26.1", features = ["derive"] } # Enum utilities
  strum_macros = "0.26.1"
