[package]
  authors.workspace    = true
  description          = "Standard library for the Typhon programming language"
  edition.workspace    = true
  license.workspace    = true
  name                 = "typhon-stdlib"
  repository.workspace = true
  version.workspace    = true

  # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
  # Core dependencies
  log       = "0.4"
  thiserror = "1.0"

  # Data structures
  fxhash = "0.2" # Fast hash implementation

  [dependencies.serde]
    features = ["derive"]
    version  = "1.0"

[dev-dependencies]
  insta    = "1.34" # Snapshot testing
  proptest = "1.3"  # Property-based testing
